### PR TITLE
🧪IMPROVE: Replaces Arjan's videos with new testing content

### LINKED ISSUE #14: Improve Testing module
### Description

The videos of Arjan are too fast, hard to search for specific topics when doing the assignment and do not explain the logic behind patching and mocking. I suggest 2 web articles which in my opinion explain better what happens when patching, mocking and using fixtures and also touch on using conftest:
- https://towardsdatascience.com/pytest-with-marking-mocking-and-fixtures-in-10-minutes-678d7ccd2f70
- https://www.tutorialspoint.com/pytest/pytest_quick_guide.htm

I also suggest this quick article which explains how to patch functions that read files, and more importantly, how to mock pandas df read function (it does it with sql query but i found it really helpful nonetheless):
- https://coderbook.com/@marcus/how-to-mock-and-unit-test-with-pandas/ 

### Why

_No response_

### How

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by MrCordeiro**
Part of the feedback we have received is that Arjan's videos were too complex.

Makes sense: Arjan focuses a lot on system design and OOP, even when writing tests, and beginners are not fully ready for that yet.

# Changes

Replaced Arjan's videos with 3 resources: an overall intro to Pytest, a video focused on mock.patch and one extra resource for fixtures
Moved all the content from the Word document to a markdown file
Expanded the testing dataframe document with comments and a better comparison helper function

### CODE REVIEW

**Comment by MrCordeiro** [comment]
@Gustavo-1300 , I'm still unsure whether to add or not this resource: https://coderbook.com/@marcus/how-to-mock-and-unit-test-with-pandas/

I like everything about it, except one thing. This section:

> I’ve seen a bunch of times where developers “mock” these things by placing actual files on the file system that they then read in. This is a terrible idea for multiple reasons:
> - By hiding the data that the test relies on in a file, you are making the test much more difficult to read and understand.
> - Files pollute your code repository and in the end, you might have tons of files that you might not even be sure of if they are in use or not.

This is simply not good advice. For the following reasons:

- His advice is only sound when dealing with very small and toy datasets
- Sometimes the data becomes too complicated with too many edge cases and too many requirements to be properly maintained as an in-memory object. This makes updating them a pain and soon enough people stop doing so.
- Consider that, when dealing with data products, business requirements are constantly evolving. Keeping up with them while creating in-memory objects is a nightmare. The alternative, running a script that samples the data into a fixture, is much easier to maintain.
- You are still polluting your repo, not with files, but with code that creates these objects. The same issue of not being sure of the testing artifacts are being used is equally valid for these objects.
- As the in-memory object grows, its only benefit disappears: it's not easier to understand a list of dicts with 100 elements than it is to understand a JSON file. Regardless, trying to see why a test fails via a fixture is an antipattern. The correct pattern is using a debugger.

If one wants to create data fixtures on the fly, a better solution would be to create a fixture factory or use something like https://mockaroo.com, but that may be out of the scope of this course.

So, here's what I'm thinking: to copy the intro, the "Why you should Mock Files and Queries" and the  "Mock Pandas Read Functions" into the "testing_dataframes" article.

What do you think?

**Comment by Gustavo-1300** [comment]
> 

I think it makes sense to add the points of the article to the markdown file, as the file talks about asserting that two spark dataframes are equal having it also describe how to to mock pandas functions in within topic.

**Review by Gustavo-1300 — APPROVED** [review]
The changes seem good, I think the new main video is much easier to follow and understand than Arjan's were. It constructs the function along the video instead of dumping all the information in the first few minutes and, in my opinion, it covers the same topics and features. The mock patch video is also a nice addition, very concise.

**Comment by MrCordeiro** [comment]
Ok, I will add the point about mocking pandas before merging. Thanks!

**Pull request merged**
